repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
    -   id: ruff
        args: [--fix]
        files: ^alma_item_checks_update_service/
    -   id: ruff-format
        files: ^alma_item_checks_update_service/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
    -   id: mypy
        files: ^alma_item_checks_update_service/
        additional_dependencies: [types-requests]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^tests/
        files: ^alma_item_checks_update_service/

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: arch -arm64 poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [--tb=short]

    -   id: pytest-cov
        name: pytest with coverage
        entry: arch -arm64 poetry run pytest --cov=alma_item_checks_update_service --cov-fail-under=90
        language: system
        pass_filenames: false
        always_run: true
        args: [--tb=short]
